---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ubuntu1604
    image: geerlingguy/docker-ubuntu1604-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra
  lint:
    name: flake8

# geerlingguy/docker-ubuntu1604-ansible
# geerlingguy/docker-ubuntu1804-ansible
# geerlingguy/docker-centos6-ansible
# geerlingguy/docker-centos7-ansible
# geerlingguy/docker-debian8-ansible
# geerlingguy/docker-debian9-ansible
